---
- name: Set common vars
  ansible.builtin.include_vars: vars/common.yml

- name: Set OS dependent variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    ansible_distribution_lts_offset: >-
      {{
        ansible_distribution_major_version|int % 2
        if ansible_distribution == "Ubuntu"
        else 0
      }}
    ansible_distribution_lts_version: >-
      {{
        ansible_distribution_major_version|int -
        ansible_distribution_lts_offset|int
        if ansible_distribution == "Ubuntu"
        else ansible_distribution_version
      }}
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_lts_version }}.yml"
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"
        - "{{ playbook_dir }}/vars"
